---
title: "kaplan-meier_plots.rmd"
author: "Grace Liu"
date: "2024-08-02"
output: html_document
---

# KM plots for ctDNA

## Baseline

```{r}
# Kaplan-Meier plots
pd_survival_by_baseline <- df_clinical_ctdna %>%
  left_join(df_ctdna_wide) %>%
  mutate(
    baseline_ctdna_level = if_else(ctdna_baseline > median(ctdna_baseline, na.rm = TRUE), 'Above Median', 'Below Median')
  )

survfit_pfs_baseline_detectable <- survfit(
  surv_progression ~ baseline_ctdna_level,
  data = pd_survival_by_baseline
)

# Plot with strata labels
p_surv_pfs_baseline_detectable <- ggsurvplot(
  survfit_pfs_baseline_detectable,
  pval = TRUE,
  legend.labs = c("Above\nMedian", "Below\nMedian"),
  title = "PFS by Baseline HPV DNA"
)

# Display plot
km1 <- plot_grid(
  p_surv_pfs_baseline_detectable$plot + theme(legend.position = 'none'),
  get_legend(
    p_surv_pfs_baseline_detectable$plot + theme(legend.position = 'right')
  ),
  rel_widths = c(7, 2)
)

ggsave("../results/Baseline_PFS_KM.png", km1, width = 4, height = 3)

```

## Midpoint

```{r fig.width = 4, fig.height = 3}

# Kaplan-Meier plots
pd_survival_by_midpoint <- df_clinical_ctdna %>%
  left_join(df_ctdna_wide) %>%
  mutate(
    midpoint_ctdna_level = if_else(ctdna_midrt > median(ctdna_midrt, na.rm = TRUE), 'Above Median', 'Below Median')
  )
survfit_pfs_midpoint_detectable <- survfit(
  surv_progression ~ midpoint_ctdna_level,
  data = pd_survival_by_midpoint
)

# Plot with strata labels
p_surv_pfs_midpoint_detectable <- ggsurvplot(
  survfit_pfs_midpoint_detectable,
  pval = TRUE,
  legend.labs = c("Above\nMedian", "Below\nMedian"),
  title = "PFS by Mid RT HPV DNA"
)

# Display plot
km1 <- plot_grid(
    p_surv_pfs_midpoint_detectable$plot + theme(legend.position = 'none'),
    get_legend(
      p_surv_pfs_midpoint_detectable$plot + theme(legend.position = 'right')
    ),
    rel_widths = c(7, 2)
  )

ggsave("../results/Mid_PFS_KM.png", km1, width = 4, height = 3)

```


## Followup

```{r}
# Kaplan-Meier plots
pd_survival_by_followup <- df_clinical_ctdna %>%
  left_join(df_ctdna_wide) %>%
  mutate(
    followup_ctdna_level = if_else(ctdna_3months > median(ctdna_3months, na.rm = TRUE), 'Above Median', 'Below Median')
  )

survfit_pfs_followup_detectable <- survfit(
  surv_progression ~ followup_ctdna_level,
  data = pd_survival_by_followup
)

# Plot with strata labels
p_surv_pfs_followup_detectable <- ggsurvplot(
  survfit_pfs_followup_detectable,
  pval = TRUE,
  legend.labs = c("Above\nMedian", "Below\nMedian"),
  title = "PFS by Follow-up HPV DNA"
)

# Display plot
km1 <- plot_grid(
  p_surv_pfs_followup_detectable$plot + theme(legend.position = 'none'),
  get_legend(
    p_surv_pfs_followup_detectable$plot + theme(legend.position = 'right')
  ),
  rel_widths = c(7, 2)
)

ggsave("../results/Followup_PFS_KM.png", km1, width = 4, height = 3)

```


# KM Plots for GTV

## preprocessing 

```{r}
df_clinical_radcure <- df_clinical_radcure %>% rename(Mrn = mrn)
df_clinical_ctdna <- df_clinical_ctdna %>% rename(Mrn = mrn)
```

```{r}
# Get the common Mrn values
common_mrn <- intersect(df_cbctfate$Mrn, df_clinical_ctdna$Mrn)

# Get the number of common Mrn values
number_of_common_patients <- length(common_mrn)
# Display the number of common patients
print(number_of_common_patients)

# df_cbctfate == 348
# df_clinical_opc == 87
# df_clinical_npc == 261

87+261
# 87 + 261 = 348 !!!

```



```{r}
# Create column for event status
# df_clinical_ctdna$status_progression
df_clinical_ctdna <- df_clinical_ctdna %>%
  mutate(status_progression = ifelse(progression == TRUE, 1, 0))

# Time to event == df_clinical_ctdna$time_to_progression

```

## Fraction 1
```{r}

# Create Strata by median for Baseline (fraction 1)
pd_survival_by_fraction1 <- df_cbctfate %>%
  filter(fraction == 1) %>% 
  left_join(df_clinical_ctdna, by = "Mrn") %>%
  mutate(
    fraction1_gtvp = if_else(smoothed > median(smoothed, na.rm = TRUE), 'Above Median', 'Below Median'),
    status_progression = ifelse(progression == TRUE, 1, 0)  # Create the status_progression column
  )

# Create survival object
surv_obj_fraction1 <- Surv(time = pd_survival_by_fraction1$time_to_progression,
                           event = pd_survival_by_fraction1$status_progression)

# Kaplan-Meier plot for Fraction 1
survfit_pfs_fraction1_detectable <- survfit(
  surv_obj_fraction1 ~ fraction1_gtvp,
  data = pd_survival_by_fraction1
)

# Plot with strata labels
p_surv_pfs_fraction1_detectable <- ggsurvplot(
  survfit_pfs_fraction1_detectable,
  pval = TRUE,
  legend.labs = c("Above\nMedian", "Below\nMedian"),
  title = "PFS by Fraction 1 GTV"
)

# Display plot
km1 <- plot_grid(
  p_surv_pfs_fraction1_detectable$plot + theme(legend.position = 'none'),
  get_legend(
    p_surv_pfs_fraction1_detectable$plot + theme(legend.position = 'right')
  ),
  rel_widths = c(7, 2)
)

ggsave("../results/Fraction1_GTV_KM.png", km1, width = 4, height = 3)

```


## Fraction 15

```{r}
# Create Strata by median for Fraction 15
pd_survival_by_fraction15 <- df_cbctfate %>%
  filter(fraction == 15) %>% 
  left_join(df_clinical_ctdna, by = "Mrn") %>%
  mutate(
    fraction15_gtvp = if_else(smoothed > median(smoothed, na.rm = TRUE), 'Above Median', 'Below Median'),
    status_progression = ifelse(progression == TRUE, 1, 0)  # Create the status_progression column
  )

# Create survival object
surv_obj_fraction15 <- Surv(time = pd_survival_by_fraction15$time_to_progression,
                            event = pd_survival_by_fraction15$status_progression)

# Kaplan-Meier plot for Fraction 15
survfit_pfs_fraction15_detectable <- survfit(
  surv_obj_fraction15 ~ fraction15_gtvp,
  data = pd_survival_by_fraction15
)

# Plot with strata labels
p_surv_pfs_fraction15_detectable <- ggsurvplot(
  survfit_pfs_fraction15_detectable,
  pval = TRUE,
  legend.labs = c("Above\nMedian", "Below\nMedian"),
  title = "PFS by Fraction 15 GTV"
)

# Display plot
km15 <- plot_grid(
  p_surv_pfs_fraction15_detectable$plot + theme(legend.position = 'none'),
  get_legend(
    p_surv_pfs_fraction15_detectable$plot + theme(legend.position = 'right')
  ),
  rel_widths = c(7, 2)
)

ggsave("../results/Fraction15_GTV_KM.png", km15, width = 4, height = 3)

```


## Fraction 20

```{r}

# Create Strata by median for Midpoint (fraction 20)
pd_survival_by_fraction20 <- df_cbctfate %>%
  filter(fraction == 20) %>% 
  left_join(df_clinical_ctdna, by = "Mrn") %>%
  mutate(
    fraction20_gtvp = if_else(smoothed > median(smoothed, na.rm = TRUE), 'Above Median', 'Below Median'),
    status_progression = ifelse(progression == TRUE, 1, 0)  # Create the status_progression column
  )

# Create survival object
surv_obj_fraction20 <- Surv(time = pd_survival_by_fraction20$time_to_progression,
                            event = pd_survival_by_fraction20$status_progression)

# Kaplan-Meier plot for Fraction 20
survfit_pfs_fraction20_detectable <- survfit(
  surv_obj_fraction20 ~ fraction20_gtvp,
  data = pd_survival_by_fraction20
)

# Plot with strata labels
p_surv_pfs_fraction20_detectable <- ggsurvplot(
  survfit_pfs_fraction20_detectable,
  pval = TRUE,
  legend.labs = c("Above\nMedian", "Below\nMedian"),
  title = "PFS by Fraction 20 GTV"
)

# Display plot
km20 <- plot_grid(
  p_surv_pfs_fraction20_detectable$plot + theme(legend.position = 'none'),
  get_legend(
    p_surv_pfs_fraction20_detectable$plot + theme(legend.position = 'right')
  ),
  rel_widths = c(7, 2)
)

ggsave("../results/Fraction20_GTV_KM.png", km20, width = 4, height = 3)

```


## Fraction 34

```{r}

# Create Strata by median for Follow-up (fraction 34)
pd_survival_by_fraction34 <- df_cbctfate %>%
  filter(fraction == 34) %>% 
  left_join(df_clinical_ctdna, by = "Mrn") %>%
  mutate(
    fraction34_gtvp = if_else(smoothed > median(smoothed, na.rm = TRUE), 'Above Median', 'Below Median'),
    status_progression = ifelse(progression == TRUE, 1, 0)  # Create the status_progression column
  )

# Create survival object
surv_obj_fraction34 <- Surv(time = pd_survival_by_fraction34$time_to_progression,
                            event = pd_survival_by_fraction34$status_progression)

# Kaplan-Meier plot for Fraction 34
survfit_pfs_fraction34_detectable <- survfit(
  surv_obj_fraction34 ~ fraction34_gtvp,
  data = pd_survival_by_fraction34
)

# Plot with strata labels
p_surv_pfs_fraction34_detectable <- ggsurvplot(
  survfit_pfs_fraction34_detectable,
  pval = TRUE,
  legend.labs = c("Above\nMedian", "Below\nMedian"),
  title = "PFS by Fraction 34 GTV"
)

# Display plot
km34 <- plot_grid(
  p_surv_pfs_fraction34_detectable$plot + theme(legend.position = 'none'),
  get_legend(
    p_surv_pfs_fraction34_detectable$plot + theme(legend.position = 'right')
  ),
  rel_widths = c(7, 2)
)

ggsave("../results/Fraction34_GTV_KM.png", km34, width = 4, height = 3)

```


## Fraction 35

```{r}

# Create Strata by median for Follow-up (fraction 35)
pd_survival_by_fraction35 <- df_cbctfate %>%
  filter(fraction == 35) %>% 
  left_join(df_clinical_ctdna, by = "Mrn") %>%
  mutate(
    fraction35_gtvp = if_else(smoothed > median(smoothed, na.rm = TRUE), 'Above Median', 'Below Median'),
    status_progression = ifelse(progression == TRUE, 1, 0)  # Create the status_progression column
  )

# Create survival object
surv_obj_fraction35 <- Surv(time = pd_survival_by_fraction35$time_to_progression,
                            event = pd_survival_by_fraction35$status_progression)

# Kaplan-Meier plot for Fraction 35
survfit_pfs_fraction35_detectable <- survfit(
  surv_obj_fraction35 ~ fraction35_gtvp,
  data = pd_survival_by_fraction35
)

# Plot with strata labels
p_surv_pfs_fraction35_detectable <- ggsurvplot(
  survfit_pfs_fraction35_detectable,
  pval = TRUE,
  legend.labs = c("Above\nMedian", "Below\nMedian"),
  title = "PFS by Fraction 35 GTV"
)

# Display plot
km35 <- plot_grid(
  p_surv_pfs_fraction35_detectable$plot + theme(legend.position = 'none'),
  get_legend(
    p_surv_pfs_fraction35_detectable$plot + theme(legend.position = 'right')
  ),
  rel_widths = c(7, 2)
)

ggsave("../results/Fraction35_GTV_KM.png", km35, width = 6, height = 3)

```




# Previous work you should ignore

## follow up

```{r fig.width = 14, fig.height = 6}
# Create plotdata_clinical_ctdna_inclusion dataframe focusing on Midpoint HPV DNA and follow-up clearance
plotdata_clinical_ctdna_inclusion <- df_clinical_ctdna %>%
  inner_join(
    df_ctdna %>%
      spread(timepoint, ctdna)
  ) %>%
  mutate(
    inclusion_status = case_when(
      is.na(`3 months`) | is.na(`Mid RT`) | `Mid RT` == 0 ~ 'Excluded',
      TRUE ~ 'Included'
    ) %>% factor(levels = c('Included', 'Excluded')),
    exclusion_reason = case_when(
      is.na(`3 months`) ~ 'Missing follow-up',
      is.na(`Mid RT`) ~ 'Missing mid-RT',
      `Mid RT` == 0 ~ 'No HPV ctDNA at Midpoint (excluded)',
      TRUE ~ 'Included in all analyses'
    ),
    hpv_detectability_midpoint = case_when(
      `Mid RT` == 0 ~ 'Undetectable',
      TRUE ~ 'Detectable'
    ),
    clearance_status = case_when(
      `3 months` == 0 ~ 'Clearance',
      `3 months` > 0 ~ 'No Clearance',
      TRUE ~ NA_character_
    )
  )

# Extract some variables
val_smoking_status_by_clearance_status <- chisq.test(
  x = plotdata_clinical_ctdna_inclusion$clearance_status,
  y = plotdata_clinical_ctdna_inclusion$smoking_status
) %>% .$p.value %>% signif(2)

val_t_category_by_clearance_status <- chisq.test(
  x = plotdata_clinical_ctdna_inclusion$clearance_status,
  y = plotdata_clinical_ctdna_inclusion$stage_t_ajcc8
) %>% .$p.value %>% signif(2)

# Kaplan-Meier plots
pd_survival_by_clearance <- df_clinical_ctdna %>%
  left_join(df_ctdna_wide) %>%
  mutate(
    clearance_status = case_when(
      `ctdna_3months` == 0 ~ 'Clearance',
      `ctdna_3months` > 0 ~ 'No Clearance',
      TRUE ~ NA_character_
    )
  )

survfit_rfs_clearance <- survfit(
  surv_recurrence ~ clearance_status,
  data = pd_survival_by_clearance
)
p_surv_rfs_clearance <- ggsurvplot(survfit_rfs_clearance, pval = T) + ggtitle('RFS by HPV DNA Clearance Status at Follow-up')

survfit_pfs_clearance <- survfit(
  surv_progression ~ clearance_status,
  data = pd_survival_by_clearance
)
p_surv_pfs_clearance <- ggsurvplot(survfit_pfs_clearance, pval = T) + ggtitle('PFS by HPV DNA Clearance Status at Follow-up')

survfit_os_clearance <- survfit(
  surv_overall ~ clearance_status,
  data = df_clinical_ctdna %>%
    left_join(df_ctdna_wide) %>%
    mutate(
      clearance_status = case_when(
        `ctdna_3months` == 0 ~ 'Clearance',
        `ctdna_3months` > 0 ~ 'No Clearance',
        TRUE ~ NA_character_
      )
    )
)
p_surv_os_clearance <- ggsurvplot(survfit_os_clearance, pval = T) + ggtitle('OS by HPV DNA Clearance Status at Follow-up')

survfit_rfs_included <- survfit(
  surv_recurrence ~ included,
  data = df_clinical_ctdna %>% mutate(included = ! patient %in% df_exclude$patient)
)
p_surv_rfs_by_inclusion <- ggsurvplot(survfit_rfs_included, pval=T) + ggtitle('RFS by inclusion status')

survfit_pfs_included <- survfit(
  surv_progression ~ included,
  data = df_clinical_ctdna %>% mutate(included = ! patient %in% df_exclude$patient)
)
p_surv_pfs_by_inclusion <- ggsurvplot(survfit_pfs_included, pval=T) + ggtitle('PFS by inclusion status')

survfit_os_included <- survfit(
  surv_overall ~ included,
  data = df_clinical_ctdna %>% mutate(included = ! patient %in% df_exclude$patient)
)
p_surv_os_by_inclusion <- ggsurvplot(survfit_os_included, pval=T) + ggtitle('OS by inclusion status')

plot_grid(
  p_surv_rfs_clearance$plot + theme(legend.position = 'none'),
  p_surv_pfs_clearance$plot + theme(legend.position = 'none'),
  p_surv_os_clearance$plot + theme(legend.position = 'none'),
  get_legend(
    p_surv_os_clearance$plot + theme(legend.position = 'right')
  ),
  p_surv_rfs_by_inclusion$plot + theme(legend.position = 'none'),
  p_surv_pfs_by_inclusion$plot + theme(legend.position = 'none'),
  p_surv_os_by_inclusion$plot + theme(legend.position = 'none'),
  get_legend(
    p_surv_os_by_inclusion$plot + theme(legend.position = 'right')
  ),
  ncol = 4,
  rel_widths = c(2,2,2,1)
)


```

# change from baseline to midpoint

```{r fig.width = 14, fig.height = 6}
# Create plotdata_clinical_ctdna_inclusion dataframe
plotdata_clinical_ctdna_inclusion <- df_clinical_ctdna %>%
  inner_join(
    df_ctdna %>%
      spread(timepoint, ctdna)
  ) %>%
  mutate(
    inclusion_status = case_when(
      is.na(`3 months`) | is.na(`Mid RT`) | `Mid RT` == 0 ~ 'Excluded',
      TRUE ~ 'Included'
    ) %>% factor(levels = c('Included', 'Excluded')),
    exclusion_reason = case_when(
      is.na(`3 months`) ~ 'Missing follow-up',
      is.na(`Mid RT`) ~ 'Missing mid-RT',
      `Mid RT` == 0 ~ 'No HPV ctDNA at Midpoint (excluded)',
      TRUE ~ 'Included in all analyses'
    ),
    hpv_detectability_midpoint = case_when(
      `Mid RT` == 0 ~ 'Undetectable',
      TRUE ~ 'Detectable'
    ),
    change_mid_baseline = `Mid RT` - Baseline,
    change_group = if_else(change_mid_baseline > median(change_mid_baseline, na.rm = TRUE), 'Above Median', 'Below Median')
  )

# Extract some variables
val_smoking_status_by_change_group <- chisq.test(
  x = plotdata_clinical_ctdna_inclusion$change_group,
  y = plotdata_clinical_ctdna_inclusion$smoking_status
) %>% .$p.value %>% signif(2)

val_t_category_by_change_group <- chisq.test(
  x = plotdata_clinical_ctdna_inclusion$change_group,
  y = plotdata_clinical_ctdna_inclusion$stage_t_ajcc8
) %>% .$p.value %>% signif(2)

# Kaplan-Meier plots
pd_survival_by_change_group <- df_clinical_ctdna %>%
  left_join(df_ctdna_wide) %>%
  mutate(
    change_mid_baseline = ctdna_midrt - ctdna_baseline,
    change_group = if_else(change_mid_baseline > median(change_mid_baseline, na.rm = TRUE), 'Above Median', 'Below Median')
  )

survfit_rfs_change_group <- survfit(
  surv_recurrence ~ change_group,
  data = pd_survival_by_change_group
)
p_surv_rfs_change_group <- ggsurvplot(survfit_rfs_change_group, pval = T) + ggtitle('RFS by Change in HPV DNA from Baseline to Midpoint')

survfit_pfs_change_group <- survfit(
  surv_progression ~ change_group,
  data = pd_survival_by_change_group
)
p_surv_pfs_change_group <- ggsurvplot(survfit_pfs_change_group, pval = T) + ggtitle('PFS by Change in HPV DNA from Baseline to Midpoint')

survfit_os_change_group <- survfit(
  surv_overall ~ change_group,
  data = df_clinical_ctdna %>%
    left_join(df_ctdna_wide) %>%
    mutate(
      change_mid_baseline = ctdna_midrt - ctdna_baseline,
      change_group = if_else(change_mid_baseline > median(change_mid_baseline, na.rm = TRUE), 'Above Median', 'Below Median')
    )
)
p_surv_os_change_group <- ggsurvplot(survfit_os_change_group, pval = T) + ggtitle('OS by Change in HPV DNA from Baseline to Midpoint')

plot_grid(
  p_surv_rfs_change_group$plot + theme(legend.position = 'none'),
  p_surv_pfs_change_group$plot + theme(legend.position = 'none'),
  p_surv_os_change_group$plot + theme(legend.position = 'none'),
  get_legend(
    p_surv_os_change_group$plot + theme(legend.position = 'right')
  ),
  ncol = 3
)

```

## Change between midpoint to followup

```{r fig.width = 14, fig.height = 6}

# Create plotdata_clinical_ctdna_inclusion dataframe focusing on Midpoint HPV DNA and follow-up clearance
plotdata_clinical_ctdna_inclusion <- df_clinical_ctdna %>%
  inner_join(
    df_ctdna %>%
      spread(timepoint, ctdna)
  ) %>%
  mutate(
    inclusion_status = case_when(
      is.na(`3 months`) | is.na(`Mid RT`) | `Mid RT` == 0 ~ 'Excluded',
      TRUE ~ 'Included'
    ) %>% factor(levels = c('Included', 'Excluded')),
    exclusion_reason = case_when(
      is.na(`3 months`) ~ 'Missing follow-up',
      is.na(`Mid RT`) ~ 'Missing mid-RT',
      `Mid RT` == 0 ~ 'No HPV ctDNA at Midpoint (excluded)',
      TRUE ~ 'Included in all analyses'
    ),
    hpv_detectability_midpoint = case_when(
      `Mid RT` == 0 ~ 'Undetectable',
      TRUE ~ 'Detectable'
    ),
    change_mid_followup = `3 months` - `Mid RT`,
    change_group = if_else(change_mid_followup > median(change_mid_followup, na.rm = TRUE), 'Above Median', 'Below Median')
  )

# Extract some variables
val_smoking_status_by_change_group <- chisq.test(
  x = plotdata_clinical_ctdna_inclusion$change_group,
  y = plotdata_clinical_ctdna_inclusion$smoking_status
) %>% .$p.value %>% signif(2)

val_t_category_by_change_group <- chisq.test(
  x = plotdata_clinical_ctdna_inclusion$change_group,
  y = plotdata_clinical_ctdna_inclusion$stage_t_ajcc8
) %>% .$p.value %>% signif(2)

# Kaplan-Meier plots
pd_survival_by_change_group <- df_clinical_ctdna %>%
  left_join(df_ctdna_wide) %>%
  mutate(
    change_mid_followup = ctdna_3months - ctdna_midrt,
    change_group = if_else(change_mid_followup > median(change_mid_followup, na.rm = TRUE), 'Above Median', 'Below Median')
  )

survfit_rfs_change_group <- survfit(
  surv_recurrence ~ change_group,
  data = pd_survival_by_change_group
)
p_surv_rfs_change_group <- ggsurvplot(survfit_rfs_change_group, pval = T) + ggtitle('RFS by Change in HPV DNA from Midpoint to Follow-up')

survfit_pfs_change_group <- survfit(
  surv_progression ~ change_group,
  data = pd_survival_by_change_group
)
p_surv_pfs_change_group <- ggsurvplot(survfit_pfs_change_group, pval = T) + ggtitle('PFS by Change in HPV DNA from Midpoint to Follow-up')

survfit_os_change_group <- survfit(
  surv_overall ~ change_group,
  data = df_clinical_ctdna %>%
    left_join(df_ctdna_wide) %>%
    mutate(
      change_mid_followup = ctdna_3months - ctdna_midrt,
      change_group = if_else(change_mid_followup > median(change_mid_followup, na.rm = TRUE), 'Above Median', 'Below Median')
    )
)
p_surv_os_change_group <- ggsurvplot(survfit_os_change_group, pval = T) + ggtitle('OS by Change in HPV DNA from Midpoint to Follow-up')

plot_grid(
  p_surv_rfs_change_group$plot + theme(legend.position = 'none'),
  p_surv_pfs_change_group$plot + theme(legend.position = 'none'),
  p_surv_os_change_group$plot + theme(legend.position = 'none'),
  get_legend(
    p_surv_os_change_group$plot + theme(legend.position = 'right')
  ),
  ncol = 3,
  rel_widths = c(2, 2, 2, 1)
)

```

## Change between baseline to followup

```{r fig.width = 12, fig.height = 6}

# Create plotdata_clinical_ctdna_inclusion dataframe focusing on Baseline HPV DNA and follow-up clearance
plotdata_clinical_ctdna_inclusion <- df_clinical_ctdna %>%
  inner_join(
    df_ctdna %>%
      spread(timepoint, ctdna)
  ) %>%
  mutate(
    inclusion_status = case_when(
      is.na(`3 months`) | is.na(`Mid RT`) | `Mid RT` == 0 ~ 'Excluded',
      TRUE ~ 'Included'
    ) %>% factor(levels = c('Included', 'Excluded')),
    exclusion_reason = case_when(
      is.na(`3 months`) ~ 'Missing follow-up',
      is.na(`Mid RT`) ~ 'Missing mid-RT',
      `Mid RT` == 0 ~ 'No HPV ctDNA at Midpoint (excluded)',
      TRUE ~ 'Included in all analyses'
    ),
    hpv_detectability_midpoint = case_when(
      `Mid RT` == 0 ~ 'Undetectable',
      TRUE ~ 'Detectable'
    ),
    change_baseline_followup = `3 months` - Baseline,
    change_group = if_else(change_baseline_followup > median(change_baseline_followup, na.rm = TRUE), 'Above Median', 'Below Median')
  )

# Extract some variables
val_smoking_status_by_change_group <- chisq.test(
  x = plotdata_clinical_ctdna_inclusion$change_group,
  y = plotdata_clinical_ctdna_inclusion$smoking_status
) %>% .$p.value %>% signif(2)

val_t_category_by_change_group <- chisq.test(
  x = plotdata_clinical_ctdna_inclusion$change_group,
  y = plotdata_clinical_ctdna_inclusion$stage_t_ajcc8
) %>% .$p.value %>% signif(2)

# Kaplan-Meier plots
pd_survival_by_change_group <- df_clinical_ctdna %>%
  left_join(df_ctdna_wide) %>%
  mutate(
    change_baseline_followup = ctdna_3months - ctdna_baseline,
    change_group = if_else(change_baseline_followup > median(change_baseline_followup, na.rm = TRUE), 'Above Median', 'Below Median')
  )

survfit_rfs_change_group <- survfit(
  surv_recurrence ~ change_group,
  data = pd_survival_by_change_group
)
p_surv_rfs_change_group <- ggsurvplot(survfit_rfs_change_group, pval = T) + ggtitle('RFS by Change in HPV DNA from Baseline to Follow-up')

survfit_pfs_change_group <- survfit(
  surv_progression ~ change_group,
  data = pd_survival_by_change_group
)
p_surv_pfs_change_group <- ggsurvplot(survfit_pfs_change_group, pval = T) + ggtitle('PFS by Change in HPV DNA from Baseline to Follow-up')

survfit_os_change_group <- survfit(
  surv_overall ~ change_group,
  data = df_clinical_ctdna %>%
    left_join(df_ctdna_wide) %>%
    mutate(
      change_baseline_followup = ctdna_3months - ctdna_baseline,
      change_group = if_else(change_baseline_followup > median(change_baseline_followup, na.rm = TRUE), 'Above Median', 'Below Median')
    )
)
p_surv_os_change_group <- ggsurvplot(survfit_os_change_group, pval = T) + ggtitle('OS by Change in HPV DNA from Baseline to Follow-up')

plot_grid(
  p_surv_rfs_change_group$plot + theme(legend.position = 'none'),
  p_surv_pfs_change_group$plot + theme(legend.position = 'none'),
  p_surv_os_change_group$plot + theme(legend.position = 'none'),
  get_legend(
    p_surv_os_change_group$plot + theme(legend.position = 'right')
  ),
  ncol = 3
)

```



